# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'btdaycase.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(993, 682)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.splitter_4 = QtGui.QSplitter(self.centralwidget)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName(_fromUtf8("splitter_4"))
        self.frame_2 = QtGui.QFrame(self.splitter_4)
        self.frame_2.setMinimumSize(QtCore.QSize(50, 0))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.widget = QtGui.QWidget(self.frame_2)
        self.widget.setMinimumSize(QtCore.QSize(33, 0))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.splitter = QtGui.QSplitter(self.widget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.list1 = QtGui.QListWidget(self.splitter)
        self.list1.setMinimumSize(QtCore.QSize(44, 44))
        self.list1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.list1.setFont(font)
        self.list1.setModelColumn(0)
        self.list1.setObjectName(_fromUtf8("list1"))
        self.tree1 = QtGui.QTreeWidget(self.splitter)
        self.tree1.setMinimumSize(QtCore.QSize(44, 44))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tree1.setFont(font)
        self.tree1.setObjectName(_fromUtf8("tree1"))
        self.tree1.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout_2.addWidget(self.splitter)
        self.verticalLayout_5.addWidget(self.widget)
        self.frame = QtGui.QFrame(self.splitter_4)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.widget_3 = QtGui.QWidget(self.frame)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.splitter_2 = QtGui.QSplitter(self.widget_3)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.frame_4 = QtGui.QFrame(self.splitter_2)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox = QtGui.QGroupBox(self.frame_4)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.widget_2 = QtGui.QWidget(self.groupBox)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tbnUp = QtGui.QToolButton(self.widget_2)
        self.tbnUp.setMinimumSize(QtCore.QSize(10, 10))
        self.tbnUp.setObjectName(_fromUtf8("tbnUp"))
        self.horizontalLayout.addWidget(self.tbnUp)
        self.tbnDown = QtGui.QToolButton(self.widget_2)
        self.tbnDown.setMinimumSize(QtCore.QSize(10, 10))
        self.tbnDown.setObjectName(_fromUtf8("tbnDown"))
        self.horizontalLayout.addWidget(self.tbnDown)
        self.tbnLeft = QtGui.QToolButton(self.widget_2)
        self.tbnLeft.setMinimumSize(QtCore.QSize(10, 10))
        self.tbnLeft.setObjectName(_fromUtf8("tbnLeft"))
        self.horizontalLayout.addWidget(self.tbnLeft)
        self.tbnRight = QtGui.QToolButton(self.widget_2)
        self.tbnRight.setMinimumSize(QtCore.QSize(10, 10))
        self.tbnRight.setObjectName(_fromUtf8("tbnRight"))
        self.horizontalLayout.addWidget(self.tbnRight)
        self.tbnAdd = QtGui.QToolButton(self.widget_2)
        self.tbnAdd.setMinimumSize(QtCore.QSize(10, 10))
        self.tbnAdd.setObjectName(_fromUtf8("tbnAdd"))
        self.horizontalLayout.addWidget(self.tbnAdd)
        self.tbnRemove = QtGui.QToolButton(self.widget_2)
        self.tbnRemove.setMinimumSize(QtCore.QSize(10, 10))
        self.tbnRemove.setObjectName(_fromUtf8("tbnRemove"))
        self.horizontalLayout.addWidget(self.tbnRemove)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.widget_2)
        self.tree2 = QtGui.QTreeWidget(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tree2.setFont(font)
        self.tree2.setObjectName(_fromUtf8("tree2"))
        self.tree2.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout.addWidget(self.tree2)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.frame_3 = QtGui.QFrame(self.splitter_2)
        self.frame_3.setMinimumSize(QtCore.QSize(50, 0))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.splitter_3 = QtGui.QSplitter(self.frame_3)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.tbl1 = QtGui.QTableView(self.splitter_3)
        self.tbl1.setObjectName(_fromUtf8("tbl1"))
        self.pteRaw1 = QtGui.QPlainTextEdit(self.splitter_3)
        self.pteRaw1.setObjectName(_fromUtf8("pteRaw1"))
        self.verticalLayout_4.addWidget(self.splitter_3)
        self.horizontalLayout_3.addWidget(self.splitter_2)
        self.verticalLayout_6.addWidget(self.widget_3)
        self.horizontalLayout_2.addWidget(self.splitter_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 993, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.tbnUp.setText(_translate("MainWindow", "...", None))
        self.tbnDown.setText(_translate("MainWindow", "...", None))
        self.tbnLeft.setText(_translate("MainWindow", "...", None))
        self.tbnRight.setText(_translate("MainWindow", "...", None))
        self.tbnAdd.setText(_translate("MainWindow", "...", None))
        self.tbnRemove.setText(_translate("MainWindow", "...", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))

