#!/usr/bin/env python

from __future__ import print_function

import os
import sys

from robotremoteserver import RobotRemoteServer


try:
    basestring
except NameError:   # Python 3
    basestring = str

rpc_count = 0

class ExampleLibrary(object):
    """Example library to be used with Robot Framework's remote server.
    This documentation is visible in docs generated by `Libdoc`.
    """
    def __init__(self):
        self.index = 0 
        pass

    def add2(self, a, b):
        """ return 2 item add """
        return (a+b)
    def count_items_in_directory(self, path):
        """Returns the number of items in the directory specified by `path`."""
        items = [i for i in os.listdir(path) if not i.startswith('.')]
        return len(items)

    def strings_should_be_equal(self, str1, str2):
        print("Comparing '%s' to '%s'." % (str1, str2))
        if not (isinstance(str1, basestring) and isinstance(str2, basestring)):
            raise AssertionError("Given strings are not strings.")
        if str1 != str2:
            raise AssertionError("Given strings are not equal.")
    def createRPC(self, config = ""):
        global rpc_count 
        print("create a rpc by config '{}'".format(config))
        rpc_count = rpc_count+1
        return rpc_count -1
        return 0
    def create_connect(self, index, addr):
        print("{}: create_connect to {}".format(index, addr))
        return 0
    def destroy_connect(self, index, reason):
        print("{}: destroy_connectto {}".format(index, reason))
        return 0 
    def send_data(self, index, data):
        print("{}: send_datato {}".format(index, data))
        return 0
    def runcase(self, index, casename, *param):
        print("runcase handle:{} casename:{} parameter:{} ".format(index, casename, " ".join(param)))
        return 0
    def runaction(self, index, casename, *param):
        print("runaction handle:{} action:{} parameter:{} ".format(index, casename, " ".join(param)))
        return 0



if __name__ == '__main__':
    RobotRemoteServer(ExampleLibrary(), *sys.argv[1:])